### ISSUE TITLE
Can't get example working due to property access modifier

### ISSUE THREAD

**Issue by henningms** [1iveowl/Simple-Http-Listener-PCL#23]
Hi,

Wanted to try this library but I can't get the example running in my app due to the HttpRepone class can't really be used outside of your own library due to the internal set access modifier. Why is this internal? Seems weird to have to copy this class to get it working..

And shouldn't HttpRepone be HttpResponse? 🤔

**Comment by trymnilsen** [comment]
+1

**Comment by 1iveowl** [comment]
Thank you. The `HttpRepone` is a typo. I'll fix it in the NeXT release. Not that it really matters, because the Internal class is not part the contract. 

Regarding usage. You need to create a class that implements the interface `IHttpResponse` (this is the real contract). This is the way the library is constructed using [dependency injection](https://stackoverflow.com/questions/130794/what-is-dependency-injection). It might add this extra requirement, but it also means that you can create you own HttpResponse class and you can btw call it whatever you like ;-)

Also, creating a class that just implements IHttpResponse is super easy in Visual Studio, so the overhead is minimal.

**Comment by 1iveowl** [comment]
I've updated the readme to better reflect this. Thank you for pointing it out.
