### ISSUE TITLE
[Question] Can the device receive file trough it?

### ISSUE THREAD

**Issue by YordanYanakiev** [1iveowl/Simple-Http-Listener-PCL#36]
Is there a way the device to receive a file trough the http listener ?

**Comment by 1iveowl** [comment]
I suppose you could use POST and then encode the  body with a file with for instance using base64 encoding. Not sure I haven't tried.

**Comment by YordanYanakiev** [comment]
I see. No raw byte sending possible ?

**Comment by 1iveowl** [comment]
I don't see why now. The Body is recieved as a stream so really up to you to do what you want with that stream. 

BTW. Please use the new version 6+ of this library. It's much improved.

**Comment by YordanYanakiev** [comment]
Great ! Thank You 1iveowl !

**Comment by 1iveowl** [comment]
Try upgrading to VS 15.8.7.

**Comment by 1iveowl** [comment]
Also, don't install the native project. Get the .Net Standard Nuget.

**Comment by YordanYanakiev** [comment]
Oh. well.. I am unable to.  Our company decided that anything above 15.4.3 is not worthy and problematic, since most of our projects is pure PCL native, and since Forms is super slow and low quality we stuck on Native, and 15.4.3 is the last one stable PCL native, so it is NO-GO situation seems like :'(

**Comment by 1iveowl** [comment]
Hmm. That makes little sense to me. NET Standard is a massive improvement over PCL and it has matured very well over the past couple of years. 

Now I don't know what your company is doing but I don't recognize Xamarin Forms as being slow either. It's massively flexible and it's even possible to mix in Native is those cases where you absolutely must. The challenge is that there's a learning curve, but I'd say that it's worth the effort.

**Comment by YordanYanakiev** [comment]
We've invested quite a lot resources and live power for moving to forms.
For a small projects it's ok, but as the project grow - the ground under forms start shaking, and the lacks start booming like a sleeping bombs. Anyway we've been there, and we declined it. Still thank You for Your efforts.

**Comment by 1iveowl** [comment]
As I mentioned, I don't know what your company is doing. Now, I been in IT since the early 90's and more often than not, I've seen these cases where some company have made these types of arguments. Sometimes rightly so, other times they turned out to be devastatingly wrong after some years. 

There is no doubt that Forms have shortcomings. However, what is typically difficult to take into account when making the decision to stick with a technology vs building you own, is how fast the technology will evolve vs your own ability to evolve and invest in what you build yourselves. Especially, when what you building yourselves is a technology is orthogonal to what is you actual business. 

What I've seen again and again is that companies are over confident is their own ability to invest.  

Again, as said,  I have no idea if this is the case here. I'm only making general reflections. And I do think that Forms is evolving fast and and that it have improved a lot this past year. And the fact alone that it is now able to utilize NET Standard rather than legacy PCL, is a big deal I think. 

Anyhow. Good luck with your project 😊
